[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.pylint.messages_control]
disable = [
    "no-self-use"
]

[tool.pylint.format]
max-line-length = 120

[tool.pylint.basic]
min-public-methods = 1
